### ISSUE TITLE
Buggy end of game

### ISSUE THREAD

**Issue by ssardina** [msardina/games-python#3]
When we lose the game, the screen closes, but the terminal takes a lot of time to finish and in the end it gives error:

```shell
 python main.py
pygame 2.1.2 (SDL 2.0.16, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/ssardina/git/courses/SEROLUMA/marcos/games-python.git/Halloween-Rampage/main.py", line 423, in <module>
    pygame.display.update()
pygame.error: video system not initialized
```

Something is wrong in the closing of the program

**Comment by ssardina** [comment]
@msardina I think I know why this is happening. Check this part:

![image](https://github.com/msardina/games-python/assets/2368384/aaf838ad-1288-43eb-965b-4e56406910a4)



In line 423 you close pygame, so the window is gone, but remember, the program is still running!. So it will run 427 and then 428, etc... the program still has code and is running, but pygame has quit, so lines like 428 are bad because there is no more active pygame

You need to also finish python completly so that after closing pygame you close the whole program, you finish! one way is to use `exit` function, goolge it!

**Comment by ssardina** [comment]
y senor @msardina , arreglo esto?

**Comment by msardina** [comment]
Dear Sir Sebastian Sardina,

Thank you for spending time reading and viewing my game. I appreciate it.
I think the reason it does this is because...

Loss timer goes over 2 and it says pygame.quit().
This pygame.quit() function quits pygame.
So when it comes down to pygame.display.update() It goes ' what the heck is
this '.
Therefore finishing with a buggy ending.

Kind regards,
from Marcos

🥰🥰

**Comment by ssardina** [comment]
Hola @msardina ! 

Thanks for addressing the bug finishing of the game. Now I still get this error now:

```python
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/ssardina/git/courses/SEROLUMA/marcos/games-python.git/Halloween-Rampage/main.py", line 326, in <module>
    score_txt = font.render(f'{score}', True, (0, 0, 0))
pygame.error: Library not initialized
```

As I said before, quiting pygame will not finish the actual Python program, it will just finish the pygame environment. For example, your while main loop that starts in 323 is still running Marcos... you need to finish well the WHOLE Python script program

**Comment by ssardina** [comment]
OK I think this has been resolved! you can close it now @msardina !
